index.js, package.json
=> PROD-3172 Initialize yarn -> master

README.md, demo/tc-app.html, demo/tc-tool-app.html, index.html, src/assets/main-navigation.json, src/lib/components/LinksMenu.svelte, src/lib/components/TcLogo.module.scss, src/lib/components/ToolSelector.module.scss, src/lib/components/ToolSelector.svelte, src/lib/components/UserArea.module.scss, src/lib/components/UserArea.svelte, src/lib/components/UserAvatar.svelte, src/lib/marketing-navigation/components/HoverMenu.module.scss, src/lib/marketing-navigation/components/HoverMenu.svelte, src/lib/tool-navigation/ToolNavigation.svelte, src/lib/tool-navigation/TopNavbar.module.scss, src/lib/tool-navigation/TopNavbar.svelte, src/lib/utils/classnames.ts, src/main.ts
This is a copy of this PR w/the updated branch name.
https://github.com/topcoder-platform/universal-navigation/pull/4
=> PROD-3171 Initiali stub nav -> master

README.md
update readme about the `update` command
=> PROD-3171 update readme -> master

src/assets/main-navigation.json, src/assets/tool-navigation.json, src/lib/config/index.ts, src/lib/functions/marketing-navigation.provider.ts, src/lib/functions/tool-navigation.provider.ts
Moves the DEFAULT_HOST into a config file so it is easier to be dynamically set at build time.
=> Make default host configurable

vite.config.ts
Updates vite.config and moves `rollupOptions` into the build config.
This will build a single js file.
=> Update vite.config -> master

.circleci/config.yml
This PR adds a deployment script for CI/CD.
=> PROD-3205 deploy script -> master

iac/uni-nav.deploy.yml
This PR configures the cloudfront distribution to automatically compress files.
=> PROD-3207 Add Compression -> master

package.json
Updates `types` in package json to point to the main.d.ts.
=> Update types' main file in package.json

.circleci/config.yml
=> PROD-3205 toggling caching again -> master

.circleci/config.yml, package-lock.json
This PR updates the config.yml to deploy to the prod environment.
It also updates the deployment script bc CircleCI could not find a specific version that AWSCLI is dependent on. I'm not totally sure why this fix works. I copied it from Learning Paths API.
=> PROD-3205 Enable PROD deployments -> master

iac/uni-nav.deploy.yml
This PR adds the community app origins for CORS.
It also cleans up some of the prod CORS definitions.
=> PROD-3158 Adds community app dev origins for CORS -> master

src/lib/config/nav-menu/menu-item.ts
[PROD-3283](https://topcoder.atlassian.net/browse/PROD-3283)
Changes the urls from "business" to "customer"
=> PROD-3283 business-customer change -> master

src/lib/footer-navigation/FooterNavigation.svelte, src/lib/marketing-navigation/MarketingNavigation.svelte, src/lib/tool-navigation/ToolNavigation.svelte, src/lib/utils/fonts.ts
[PROD-3280](https://topcoder.atlassian.net/browse/PROD-3280)
This PR adds a utility method to check and load fonts when they are missing.
The method is returning a promise that resolves a single time - when the fonts have been loaded.
As a result [PROD-3273](https://topcoder.atlassian.net/browse/PROD-3273) should also be fixed.
=> PROD-3280 Add utility to check & load fonts when they are missing -> master

README.md, iac/uni-nav.deploy.yml
This PR adds the TopCrowd origins for CORS.
It also updates the README for CORS.
=> PROD-3285 Adds TopCrowd/PTC origins to Uni Nav -> master

src/lib/config/nav-menu/tool-selector-nav-items.ts
https://topcoder.atlassian.net/browse/PROD-3292
Updates link for discussions
=> PROD-3292 - update discussions link -> master

src/lib/components/tool-selector/ToolMenu.module.scss, src/lib/styles/main.scss
2 small integration fixes:
- right now the svg sprite located in the tools menu is actually taking some height space, this will make the sprite take 0 height
- fixes the hover color for links
=> Integration fixes -> master

src/lib/components/TcLogo.svelte, src/lib/components/TopNavbar.module.scss, src/lib/components/TopNavbar.svelte, src/lib/footer-navigation/FooterBottomBar.module.scss, src/lib/footer-navigation/FooterBottomBar.svelte, src/lib/footer-navigation/FooterNavigation.module.scss, src/lib/marketing-navigation/components/HoverMenu.module.scss, src/lib/styles/_mixins.scss
Fix navigation width on larger screens according to latest figma
=> Fix navigation width on larger scresn according to latest figma -> master

src/lib/components/MobileMenu.svelte
https://topcoder.atlassian.net/browse/PROD-3338
Automatically calls (on mount) the function that calculates the correct value for the `vh` unit on mobile.
=> PROD-3338 - fix for mobile height -> master

src/lib/config/nav-menu/footer-nav-items.ts, src/lib/config/nav-menu/menu-item.ts, src/lib/config/nav-menu/tool-selector-nav-items.ts
https://topcoder.atlassian.net/browse/PROD-3305
Renames Community to Talent and Business to Customer in navigation
=> PROD-3305 - rename community to talent and business to customer

public/assets/icon-tool.svg, src/lib/components/tool-selector/ToolMenu.module.scss, src/lib/components/tool-selector/ToolMenu.svelte, src/lib/components/tool-selector/ToolSelector.svelte, src/lib/config/nav-menu/tool-selector-nav-items.ts
https://topcoder.atlassian.net/browse/PROD-3317
Updates the tool select dropdown menu according to latest figma and details in the ticket PROD-3317.
It also adds a prefetch for the svg sprite image - in the _hopes_ the icons will be ready when you hover the tool selector.
=> PROD-3324 - update Tools selector menu -> master

src/lib/config/nav-menu/tool-selector-nav-items.ts
https://topcoder.atlassian.net/browse/PROD-3371
Updates the url for the arena tool & payments.
=> PROD-3371 - update url for arena tool -> master

src/lib/components/PopupMenu.module.scss, src/lib/components/tool-selector/ToolMenu.module.scss
Related tickets:
https://topcoder.atlassian.net/browse/PROD-3395
https://topcoder.atlassian.net/browse/PROD-3396
Limits the height that popups can take.
=> PROD-3395, PROD-3396 - limit popups height -> master

src/lib/styles/main.scss
Related tickets:
https://topcoder.atlassian.net/browse/PROD-3382
https://topcoder.atlassian.net/browse/PROD-3378
https://topcoder.atlassian.net/browse/PROD-3384
Updates the rules for links under uni-nav to overwrite integrations rules.
after:
=> PROD-3382 - update links styling -> master

src/lib/tool-navigation/ToolNavigation.svelte, src/lib/utils/use-storage.ts
https://topcoder.atlassian.net/browse/PROD-3383
Fixes the loading animation for the expandable part in the tool navigation. This was causing a "flickering" effect when navigating between pages, now should be fixed.
=> PROD-3383 - Fix loading animation for the tool navivation

src/lib/components/PopupMenu.module.scss
Related tickets:
https://topcoder.atlassian.net/browse/PROD-3395
https://topcoder.atlassian.net/browse/PROD-3396
Limits the height that popups can take.
=> fix height for popup

.circleci/config.yml
This PR cleans up the Circle CI config to deploy master and dev branches to prod and dev environments, respectively.
=> PROD-3458 Production Deployment config -> dev

iac/uni-nav.deploy.yml
This PR adds localhost for CORS in dev.
=> PROD-3318 localhost CORS for customer marketing -> dev

.circleci/config.yml, iac/uni-nav.deploy.yml
This PR adds the CI config that increments the version number and adds they types when there is a push to master.
=> TCA-838 2.5 TCA Uni-Nav Release Increment Version & Types -> master

iac/uni-nav.deploy.yml
Add allowed origin for James Marquez local wordpress env.
=> PROD-3264 CORS

iac/uni-nav.deploy.yml
This commit adds 2 local origins to the allowed origins for Dev instance of Uni Nav
=> PROD-3264 integrate wp

src/lib/config/nav-menu/nav-items.dev.config.ts
This PR sets the URLs for the dev nav to use permalinks.
NOTE: There will be a subsequent PR that updates the prod config. I just wanted to get this into dev asap.
=> PROD-3264 Update dev nav config w/permalinks -> dev

src/lib/utils/routes.ts
Updates the getActiveRoute to account for the full url in the routes & for the trailing slash
=> PROD-3264 - Update the getActiveRoute method

src/lib/marketing-navigation/MarketingNavigation.svelte
At the moment the active route is not showing up for the marketing navigation.
This PR fixes the active route displaying.
=> Watch for active route changes

src/lib/config/nav-menu/marketing-nav-items.ts, src/lib/config/nav-menu/nav-items.dev.config.ts, src/lib/config/nav-menu/nav-items.prod.config.ts, src/lib/marketing-navigation/components/HoverMenu.module.scss, src/lib/marketing-navigation/components/HoverMenu.svelte
https://topcoder.atlassian.net/browse/PROD-3506
Updates the marketing nav items according to latest figma.
=> PROD-3506 update uninav marketing items according to latest figma

src/lib/styles/main.scss
Fixes the hover styling for navigation - increases the css specificity.
=> Fix links stylings

src/lib/components/tool-selector/ToolMenu.module.scss, src/lib/components/tool-selector/ToolMenu.svelte
https://topcoder.atlassian.net/browse/PROD-3463
https://topcoder.atlassian.net/browse/PROD-3465
Increases the hit area for the links in the tools menu and opens the apps in new tabs
=> PROD-3463 , PROD-3465 - Increases the hit area. open new tabs -> dev

src/lib/config/nav-menu/nav-items.dev.config.ts
Some of the urls had 'hhttps' instead of 'https', fixed them.
=> Fix issue with urls

src/lib/components/user-area/UserArea.module.scss, src/lib/components/user-area/UserArea.svelte, src/lib/config/nav-menu/nav-item-config.model.ts, src/lib/config/nav-menu/nav-items.dev.config.ts, src/lib/config/nav-menu/nav-items.prod.config.ts, src/lib/marketing-navigation/components/NavigationBar.module.scss, src/lib/marketing-navigation/components/NavigationBar.svelte, types/src/lib/config/nav-menu/nav-item-config.model.d.ts
https://topcoder.atlassian.net/browse/PROD-3412
Adds about us link in the marketing navigation
=> PROD-3412 - add about us for the marketing navigation -> dev

src/lib/config/nav-menu/footer-nav-items.ts, src/lib/config/nav-menu/nav-item-config.model.ts, src/lib/config/nav-menu/nav-items.dev.config.ts, src/lib/config/nav-menu/nav-items.prod.config.ts, types/src/lib/config/nav-menu/nav-item-config.model.d.ts
https://topcoder.atlassian.net/browse/PROD-3523
Updates footer with latest links/urls
=> PROD-3523 update footer -> dev

src/lib/components/LinksMenu.module.scss, src/lib/marketing-navigation/MarketingNavigation.svelte, src/lib/marketing-navigation/components/HoverMenu.module.scss, src/lib/marketing-navigation/components/HoverMenu.svelte, src/lib/marketing-navigation/components/NavigationBar.svelte
https://topcoder.atlassian.net/browse/PROD-3511
Adds hover & active states for the links in the "mega menu"
=> PROD-3511 - add active & hover state for the "mega menu" -> dev

src/lib/components/LinksMenu.svelte, src/lib/marketing-navigation/MarketingNavigation.svelte, src/lib/marketing-navigation/components/NavigationBar.svelte
https://topcoder.atlassian.net/browse/PROD-3517
https://topcoder.atlassian.net/browse/PROD-3516
https://topcoder.atlassian.net/browse/PROD-3519
https://topcoder.atlassian.net/browse/PROD-3560
Updates the behavior of showing the hover menu for the navigation:
- last nav level will always have a hover menu.
=> PROD-3560 - update how we show hover menu -> dev

src/lib/config/nav-menu/nav-items.dev.config.ts
https://topcoder.atlassian.net/browse/PROD-3564
Updates the url for the data-science, bfsi, communications nav links
=> PROD-3564 - update url for data-science -> dev

src/lib/config/nav-menu/nav-items.prod.config.ts
https://topcoder.atlassian.net/browse/PROD-3581
Fixes the production link for the Online Review Tool.
=> PROD-3581 fix OR link -> master

src/lib/footer-navigation/FooterNavigation.svelte
https://topcoder.atlassian.net/browse/PROD-3558
Scrolls footer into view when expanding it.
THIS IS FOR NEXT RELEASE, DO NOT MERGE YET
=> PROD-3558 - scroll footer into view when expanding -> dev

src/lib/marketing-navigation/components/HoverMenu.module.scss
https://topcoder.atlassian.net/browse/PROD-3516
Updates font size for navigation link description paragraph
=> PROD-3516 - update navlink description font size -> dev

src/lib/components/Accordion.module.scss, src/lib/components/Button.module.scss, src/lib/components/LinksMenu.module.scss, src/lib/components/forms/InputWrap.module.scss, src/lib/components/modals/Modal.module.scss, src/lib/components/modals/SupportModal.module.scss, src/lib/components/tool-selector/ToolMenu.module.scss, src/lib/components/user-area/UserAvatar.module.scss, src/lib/components/user-area/UserMenu.module.scss, src/lib/footer-navigation/FooterBottomBar.module.scss, src/lib/footer-navigation/FooterNavigation.module.scss, src/lib/marketing-navigation/components/HoverMenu.module.scss, src/lib/mobile-navigation/MobileNavigation.module.scss, src/lib/styles/_fonts.scss, src/lib/tool-navigation/ToolNavigation.module.scss
https://topcoder.atlassian.net/browse/PROD-3369
This PR tries to fix the "flashing" of font face by trying to fallback to the same font that's already loaded in the community app but has a different name (it's loaded as "BarlowCondensed" instead of "Barlow Condensed").
=> PROD-3369 - fallback fontname  -> dev

src/lib/config/nav-menu/marketing-nav-items.ts, src/lib/config/nav-menu/nav-items.dev.config.ts, src/lib/config/nav-menu/nav-items.prod.config.ts
https://topcoder.atlassian.net/browse/PROD-3522
Adds "challenge model" nav item
=> PROD-3522 - add "challenge model" nav item

src/README.md
Updates the README.md with details about why svelte was chosen for creating the uni-nav
=> PROD-3493 readme

src/lib/components/TcLogo.svelte, src/lib/config/index.ts, src/lib/config/nav-menu/nav-item-config.model.ts, src/lib/config/nav-menu/nav-items.dev.config.ts, src/lib/config/nav-menu/nav-items.prod.config.ts, src/lib/functions/support/support.service.ts, src/lib/utils/paths.ts, types/src/lib/config/index.d.ts, types/src/lib/config/nav-menu/nav-item-config.model.d.ts
This PR updates the homepage link so that it goes to the correct URL for the env.
=> PROD-3567 Update homepage link -> dev

src/lib/components/TopNavbar.module.scss, src/lib/components/VerticalSeparator.module.scss, src/lib/components/VerticalSeparator.svelte, src/lib/components/user-area/UserArea.svelte, src/lib/marketing-navigation/components/AboutUsMenuItem.svelte
https://topcoder.atlassian.net/browse/PROD-3593
Adds vertical separator in topbar
=> PROD-3593 - add vertical separator in topbar -> dev

src/lib/footer-navigation/FooterNavigation.module.scss, src/lib/styles/_mixins.scss
https://topcoder.atlassian.net/browse/PROD-3584
Pushes last 2 footer sections to last column (desktop only)
=> PROD-3584 - push last 2 footer sections to last column

iac/uni-nav.deploy.yml
This PR adds the following origins for CORS:
dev:
https://challenges.topcoder-dev.com
prod:
https://challenges.topcoder.com
=> PROD-3622 Add Challenges CORS -> dev

src/lib/config/nav-menu/nav-items.dev.config.ts, src/lib/config/nav-menu/nav-items.prod.config.ts
https://topcoder.atlassian.net/browse/PROD-3606
https://topcoder.atlassian.net/browse/PROD-3598
Fixes typos in nav
=> PROD-3606 PROD-3598 fix typos

iac/uni-nav.deploy.yml
Adds CORS entry for connect.topcoder(-dev).com
=> PROD-3685 Adds CORS entry for Connect > dev

src/lib/marketing-navigation/components/AboutUsMenuItem.svelte
This PR hides the About Us link in the top nav for mobile browsers.
=> PROD-3669 Hide About Us on Mobile -> dev

iac/uni-nav.deploy.yml
This PR adds all the origins to support TopCrowd.
=> PROD-3462 TopCrowd CORS -> dev

src/lib/config/nav-menu/marketing-nav-items.ts, src/lib/config/nav-menu/nav-item-config.model.ts, src/lib/config/nav-menu/nav-items.config.ts, types/src/lib/config/nav-menu/nav-item-config.model.d.ts
https://topcoder.atlassian.net/browse/PROD-3690
Adds url in marketing nav for talent/the-community.
=> PROD-3690 the community page

src/lib/components/Accordion.svelte
https://topcoder.atlassian.net/browse/PROD-3738
Fixes mobile navigation for some of the pages that don't have children to render.
=> PROD-3738 - fix mobile nav child renderer -> dev

src/lib/config/nav-menu/footer-nav-items.ts, src/lib/config/nav-menu/nav-items.config.ts
https://topcoder.atlassian.net/browse/PROD-3725
https://topcoder.atlassian.net/browse/PROD-3694
Fixes nav item urls for TC academy WP page and for website-design.
=> Prod 3725 fix urls -> dev

src/lib/config/nav-menu/marketing-nav-items.ts
https://topcoder.atlassian.net/browse/PROD-3725
Updates the link for TopcoderAcademy to point to platform-ui/learn
=> PROD-3725 - update tca-link to platform-ui app -> dev

src/lib/components/user-area/UserMenu.svelte, src/lib/config/nav-menu/index.ts, src/lib/config/nav-menu/nav-items.config.ts, types/src/lib/config/nav-menu/index.d.ts, uni-nav.env.dev, uni-nav.env.prod
https://topcoder.atlassian.net/browse/PROD-3768
Updates the links for the pages created in community app
=> PROD-3768 - update community page links -> dev

src/lib/config/nav-menu/nav-items.config.ts, src/lib/config/nav-menu/tool-selector-nav-items.ts
https://topcoder.atlassian.net/browse/PROD-3771
Updates url to articles when opened from the tool selector - send nav type as parameter.
Updates url for challenges to use the qa/dev environemnt
=> PROD-3771 update link for articles & challenges -> dev

src/lib/components/LinksMenu.svelte, src/lib/config/nav-menu/nav-items.config.ts, src/lib/marketing-navigation/components/HoverMenu.svelte
https://topcoder.atlassian.net/browse/PROD-3772
https://topcoder.atlassian.net/browse/PROD-3769
Opens Book a Demo and Talk to an Expert in new tabs
Updates the url for book a demo link.
=> PROD-3772 - open demo & talk to expert in new tab -> dev

src/lib/footer-navigation/FooterNavigation.svelte
https://topcoder.atlassian.net/browse/PROD-3720
Hides the full navigation in the mobile footer.
=> PROD-3720 - hide full nav in mobile -> dev

src/lib/components/modals/SupportModal.svelte
https://topcoder.atlassian.net/browse/PROD-3848
Fixes double whitespace in support modal
=> PROD-3848 - fix typo in support modal -> dev

src/lib/config/nav-menu/nav-items.config.ts
https://topcoder.atlassian.net/browse/PROD-3843
Fixes url for talk to sales link in footer
=> PROD-3843 - fix talk-to-sales url -> dev

src/lib/config/nav-menu/nav-items.config.ts
https://topcoder.atlassian.net/browse/PROD-3905
https://topcoder.atlassian.net/browse/PROD-3906
Fixes 2 spelling / text issues
=> Typo fixes -> dev

src/lib/marketing-navigation/components/HoverMenu.module.scss
https://topcoder.atlassian.net/browse/PROD-3974
Updates font weight on hover
=> PROD-3974 - update font weight on hover

uni-nav.env.prod
Updates comment on the env prod file
=> Update env prod comment -> dev

.circleci/config.yml
This reverts commit 85383cbe984f95c8efd98f37bf2750f9faf5e5f8.
Reverts the commented CI steps.
=> Revert "Comments out types update for hotfix deploy" -> dev

src/lib/config/nav-menu/nav-items.config.ts
[PROD-3598](https://topcoder.atlassian.net/browse/PROD-3598)
Fixes typo in nav item
[PROD-3598]: https://topcoder.atlassian.net/browse/PROD-3598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PROD-3598 fix typo -> dev

src/lib/config/nav-menu/nav-item-config.model.ts, src/lib/config/nav-menu/nav-items.config.ts, types/src/lib/config/nav-menu/nav-item-config.model.d.ts
https://topcoder.atlassian.net/browse/PROD-4060
Updates description for topcrowd marketing nav item
=> PROD-4060 - update description for topcrowd marketing nav item -> dev

src/lib/components/LinksMenu.svelte, src/lib/marketing-navigation/MarketingNavigation.svelte, src/lib/marketing-navigation/components/HoverMenu.module.scss, src/lib/tool-navigation/ToolNavigation.svelte
https://topcoder.atlassian.net/browse/PROD-4011
Updates behavior for the marketing hover menu: show it on all levels/nav items, except the active nav item.
=> PROD-4011 hover menu behavior -> dev

src/lib/config/nav-menu/tool-selector-nav-items.ts
https://topcoder.atlassian.net/browse/PROD-4034
Adds the topcrowd tool app
=> PROD-4034 - add topcrowd tool app -> dev

README.md, index.html, src/lib/app-context/app-context.functions.ts, src/lib/app-context/auth-config.model.ts, src/lib/components/user-area/UserArea.svelte, src/lib/functions/user-profile.provider.ts, src/main.ts, types/src/lib/app-context/app-context.functions.d.ts, types/src/lib/app-context/auth-config.model.d.ts, types/src/lib/functions/user-profile.provider.d.ts, types/src/main.d.ts
https://topcoder.atlassian.net/browse/PROD-3901
Allows user to send `user: 'auto'` (documented in README.md) parameter to instruct uni-nav to automatically fetch user data from the jwt cookie.
=> PROD-3901 fetch user profile -> dev

src/lib/functions/user-profile.provider.ts
https://topcoder.atlassian.net/browse/PROD-4078
Fixes jwt decode function
=> PROD-4078 - fix base64 decode -> dev

src/lib/functions/user-profile.provider.ts
https://topcoder.atlassian.net/browse/PROD-4078
Updates the jwt decode function
=> PROD-4078 - update jwt parser -> dev

src/lib/functions/user-profile.provider.ts
https://topcoder.atlassian.net/browse/PROD-4078
Handle no cookie
=> PROD-4078 - handle no cookie

src/lib/components/modals/Modal.svelte, src/lib/components/modals/SubmitBugModal.svelte, src/lib/components/modals/SupportModal.svelte, src/lib/config/nav-menu/footer-nav-items.ts, src/lib/config/nav-menu/nav-item-config.model.ts, src/lib/config/nav-menu/nav-items.config.ts, src/lib/footer-navigation/FooterNavigation.svelte, types/src/lib/config/nav-menu/nav-item-config.model.d.ts
https://topcoder.atlassian.net/browse/PROD-3299
Adds a secondary support modal for submitting a bug.
=> PROD-3299 - report a bug modal -> dev

src/lib/components/tool-selector/ToolMenu.module.scss
https://topcoder.atlassian.net/browse/PROD-4070
Fixes view for tool switcher in connect app.
before:
fixed:
=> PROD-4070 - fix tool switcher -> dev

src/lib/components/forms/Input.module.scss, src/lib/components/forms/Input.svelte, src/lib/components/forms/InputWrap.module.scss
https://topcoder.atlassian.net/browse/PROD-4080
https://topcoder.atlassian.net/browse/PROD-4081
Fixes UI issues with the support & report a bug modals:
- slightly cropped text in textarea
- inputs show double borders in certain apps
=> PROD-3299 fix UI issues in report a bug modal -> dev

iac/uni-nav.deploy.yml
Adds cors headers for `https://go.topcoder.com`
=> Add cors for go.topcoder.com

iac/uni-nav.deploy.yml
Update cors rules for unbounce
=> update cors for unbounce

package-lock.json, package.json
Synchronizes dev with latest from master (version update)
=> Synchronize dev with latest from master (version update)

src/lib/styles/_fonts.scss, src/lib/styles/main.scss, types/src/lib/config/nav-menu/nav-item-config.model.d.ts, types/src/lib/utils/routes.d.ts
HOTFIX PR to master, fixes issue that breaks view for uninav in formus integration.
https://topcoder.atlassian.net/browse/UN-678
Overrides css that comes from main apps and breaks styling within uninav
Adds fallback font family
=> UN-678 - override custom css, add fallback font family -> master

iac/uni-nav.deploy.yml, package-lock.json, package.json, src/lib/styles/_fonts.scss, src/lib/styles/main.scss
Synchronizes dev with latest from master:
- version update
- fix spacing for main nav in marketing menu https://topcoder.atlassian.net/browse/UN-678
- add fallback font family
=> Synchronize dev with latest from master

src/lib/components/LinksMenu.svelte, src/lib/config/nav-menu/nav-items.config.ts, src/lib/marketing-navigation/components/HoverMenu.module.scss
https://topcoder.atlassian.net/browse/UN-143
Removes the description for the "about us" nav item.
Hides hover menu when a navItem doesn't have description (do not show blank hover menu)
=> UN-143 - remove hover menu for about us -> dev

src/lib/components/tool-selector/ToolMenu.module.scss, src/lib/components/user-area/UserMenu.module.scss, src/lib/components/user-area/UserMenu.svelte, src/lib/utils/routes.ts, types/src/lib/utils/routes.d.ts
https://topcoder.atlassian.net/browse/UN-686
Updates the active and hover states in the tool switcher
=> UN-686 - update nav links states -> dev

src/lib/config/nav-menu/footer-nav-items.ts, src/lib/config/nav-menu/nav-item-config.model.ts, src/lib/config/nav-menu/nav-items.config.ts, src/lib/config/nav-menu/tool-selector-nav-items.ts, types/src/lib/config/nav-menu/nav-item-config.model.d.ts
https://topcoder.atlassian.net/browse/UN-142
Updates talk to sales & book a demo to open in the same web tab.
=> UN-142 - open pages with uninav in same tab -> dev

src/lib/components/tool-selector/ToolMenu.svelte, src/lib/components/tool-selector/ToolSelector.svelte, src/lib/components/user-area/UserArea.svelte, src/lib/functions/auth.routes-filters.ts, src/lib/functions/tool-selector-menu.provider.ts, types/src/lib/functions/auth.routes-filters.d.ts, types/src/lib/functions/tool-selector-menu.provider.d.ts
https://topcoder.atlassian.net/browse/UN-203
Automatically fetches the user's roles from the auth JWT, instead of relying on each application sending in the roles.
=> UN-203 toolswitcher based on user role -> dev

src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/main-navigation.config.ts
https://topcoder.atlassian.net/browse/UN-716
Removes Topcoder Open from the menus.
=> UN-716 - remove TCO from menu -> dev

src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/footer-nav-items.ts
https://topcoder.atlassian.net/browse/UN-723
Adds TCO menu item to footer
=> UN-723 - adds tco menu item to footer -> dev

src/lib/components/tool-selector/ToolMenu.module.scss, src/lib/config/auth.ts, src/lib/functions/auth.routes-filters.ts, src/lib/functions/user-profile.provider.ts, types/src/lib/config/auth.d.ts, types/src/lib/functions/user-profile.provider.d.ts
https://topcoder.atlassian.net/browse/UN-203
Renders the whole tool switcher menu when user doesn't have any of the "Topcoder Talent" or "Topcoder Customer" roles.
Also, removes the section title when user has assigned any of the roles.
=> UN-203 - render the whole menu when user has no specific role assigned -> dev

README.md, src/lib/app-context/app-context.functions.ts, src/lib/functions/integrations/chameleon.ts, src/lib/functions/integrations/sprig.ts, src/lib/functions/integrations/utils.ts, src/main.ts, types/src/lib/app-context/app-context.functions.d.ts, types/src/lib/functions/integrations/chameleon.d.ts, types/src/lib/functions/integrations/sprig.d.ts, types/src/lib/functions/integrations/utils.d.ts, types/src/main.d.ts
https://topcoder.atlassian.net/browse/TCA-1187
Adds parameter option to disable integrations with sprig and/or chameleon.
=> TCA-1187 - adds param options to disable sprig/chameleon -> dev

src/lib/footer-navigation/FooterNavigation.svelte
Makes the tool footer expanded by default
=> UN-733 - show the tool footer as expanded by default -> dev

iac/uni-nav.deploy.yml
Adds support for local domains for the new subdomains:
- academy.local.topcoder-dev.com
- work.local.topcoder-dev.com
- devcenter.local.topcoder-dev.com
- gamification-admin.local.topcoder-dev.com
=> Add support for local domains -> dev

package-lock.json, package.json
=> Sync Master into dev

iac/deploy-stack.sh, iac/uni-nav.deploy.yml
Removes requirement for `.env` file and sets the DOMAIN env var dynamically from the passed in deployment stage.
Also cleans up formatting of the CloudFormation YML template.
=> Updates deploy script to set domain from stage

src/lib/config/hosts.ts
=> Code cleanup: remove console entry

src/lib/components/user-area/Completedness.svelte, src/lib/nudge-app/toast-manager.ts, src/lib/utils/cookies.ts
I just realized the cookies need to be set and shared between all subdomains of topcoder.com. this fixes that.
=> MP-70 - User profile nudges & toasts

src/lib/nudge-app/Nudge.svelte, src/lib/nudge-app/components/Toastr.svelte, src/lib/nudge-app/config.ts, types/src/lib/nudge-app/config.d.ts
Adds the user handle to the url for the profile
=> MP-70 - User profile - Add user handle to toast url

src/lib/components/user-area/UserArea.svelte, src/lib/components/user-area/UserAvatar.module.scss, src/lib/functions/user-profile.provider.ts, types/src/lib/functions/user-profile.provider.d.ts
If user has customer role, do not show the profile completeness nudges & toasts.
=> MP-70 - hide the completeness nudges when user is customer -> dev

src/lib/components/sticky/Sticky.module.scss, src/lib/components/sticky/Sticky.svelte, src/lib/nudge-app/Nudge.svelte
https://topcoder.atlassian.net/browse/MP-161
Make the toast messages stick to the top of the page when scrolling down
=> MP-161 - make toasts sticky -> dev

src/lib/nudge-app/Nudge.module.scss, src/lib/styles/main.scss, src/lib/tool-navigation/ToolNavigation.svelte, src/main.ts, types/src/lib/config/hosts.d.ts
Positions the profile nudges toast below the first navbar.
=> MP-164 - profile nudges toasts positioning -> dev

src/lib/components/user-area/Completedness.module.scss, src/lib/nudge-app/Nudge.module.scss, src/lib/nudge-app/components/Toastr.module.scss
Improvments for mobile for profile nudges
=> Improve profile nudges on mobile -> dev

src/lib/components/user-area/UserAvatar.module.scss
adds white background to profile picture
=> MP-248 - profile picture bg -> dev

iac/uni-nav.deploy.yml
Adds the required CORS headers for the onboarding app
=> Add CORS headers for onboarding app -> dev

src/lib/config/nav-menu/all-nav-items.config.ts
https://topcoder.atlassian.net/browse/PROD-4338
Adds link for ChangeLog page in footer
=> PROD-4338 - add change log link in footer -> dev

src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/main-navigation.config.ts
https://topcoder.atlassian.net/browse/PROD-4395
Adds link for topcrowd universities
=> PROD-4395 Add link for topcrowd universities -> dev

.circleci/config.yml
Removes the `&update_types` step in prod deployment
=> CI config: remove &update_types step

.circleci/config.yml
Comments the PROD automatic version patching
=> CI config: comment prod auto version patch

src/lib/config/index.ts, src/lib/functions/integrations/userflow.ts, types/src/lib/config/index.d.ts
Adds config value to disable userflow (this allows to easier enable/disable it in the code)
=> Add config value for disabling userflow -> dev

src/lib/config/index.ts
=> Disable userflow by default

src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/main-navigation.config.ts
https://topcoder.atlassian.net/browse/IC-19 - Update the UniNav with Innovation Challenges links
=> IC-19 - add innovation challenges link -> dev

iac/uni-nav.deploy.yml, src/lib/config/hosts.ts, src/lib/config/nav-menu/all-nav-items.config.ts
Replace PACTS app with Wallet app (part of platform-ui)
=> CORE-97 - add wallet app -> dev

src/lib/config/index.ts
A low enough limit of MAUs has been reached, let's re-enable userflow.
=> Re-enable userflow -> master

src/lib/config/index.ts
This enables userflow (I did a mistake on last PR and it didn't get enabled).
=> Enable userflow

src/lib/config/hosts.ts, src/lib/config/nav-menu/all-nav-items.config.ts, types/src/lib/config/hosts.d.ts
This PR replaces the PACTS app in the rainbow menu with the Wallet app.
=> Release 02/15/2024 - Wallet app release

src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/footer-nav-items.ts, src/lib/config/nav-menu/tool-selector-nav-items.ts
https://topcoder.atlassian.net/browse/CORE-333 - a few updates to the user's rainbow tool switcher
https://topcoder.atlassian.net/browse/CORE-348 - Add Image Policy in footer
=> CORE-333 - Update rainbow menu -> dev

src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/footer-nav-items.ts, src/lib/config/nav-menu/main-navigation.config.ts
https://topcoder.atlassian.net/browse/TOP-838 - Remove Jira app from footer
https://topcoder.atlassian.net/browse/TOP-839 - Remove Jira app from main navi
=> TOP-838 remove jira app link

src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/main-navigation.config.ts
https://topcoder.atlassian.net/browse/TOP-1110 - Remove all sub headers and menu items from the Topcoder.com header
https://topcoder.atlassian.net/browse/TOP-1104 - Update Topcoder.com header to include Pricing and Demos
=> TOP-1110 - remove all submenus and add pricing & demo

src/lib/config/nav-menu/all-nav-items.config.ts
As per https://topcoder.atlassian.net/browse/TOP-1083
=> TOP-1083 update platform link

src/lib/config/nav-menu/all-nav-items.config.ts
https://topcoder.atlassian.net/browse/TOP-1205 - Remove the links to Releases and Changelog from the topcoder.com footer and replace with Release Notes
=> TOP-1205 - add release notes link in footer

src/lib/components/Button.module.scss, src/lib/components/LinksMenu.module.scss, src/lib/components/TopNavbar.module.scss, src/lib/components/TopNavbar.svelte, src/lib/components/VerticalSeparator.module.scss, src/lib/components/tool-selector/ToolMenu.module.scss, src/lib/components/user-area/UserArea.module.scss, src/lib/styles/_colors.scss, src/lib/tool-navigation/ToolNavigation.module.scss, src/lib/tool-navigation/tool-nav-separator/ToolNavSeparator.module.scss
https://topcoder.atlassian.net/browse/TOP-1464 - Change uninav color
Updated the color & feel of the uninav topbar, both for the marketing & tool navigation:
- marketing:
- tool:
=> TOP-1464 - change uninav colors -> dev

src/lib/footer-navigation/FooterNavigation.module.scss, src/lib/footer-navigation/FooterNavigation.svelte
Restricts the footer logo's clickable area to the visible area (it was the whole line before).
=> Fix footer logo link

.circleci/config.yml, src/lib/components/Banner.module.scss, src/lib/components/Banner.svelte, src/lib/config/banners.config.ts, src/lib/functions/integrations/userflow.ts, src/lib/marketing-navigation/MarketingNavigation.svelte, types/src/lib/config/banners.config.d.ts
https://topcoder.atlassian.net/browse/TOP-1669 - show the lab45's ai banner on all wordpress pages (marketing menu) for both logged in and not logged in users. 
This will replace the Userflow banner for the wordpress pages.
Currently everything is "hardcoded", because there's no reusing for now. If we plan to reuse this feature, we can extend later on.
=> TOP-1669 add lab45 banner

src/lib/components/MobileMenu.svelte, src/lib/components/TopNavbar.svelte, src/lib/components/user-area/SigninPopup.svelte, src/lib/components/user-area/UserArea.svelte, src/lib/config/hosts.ts, src/lib/config/index.ts, src/lib/marketing-navigation/components/NavigationBar.svelte, src/lib/tool-navigation/ToolNavigation.svelte, types/src/lib/config/hosts.d.ts
https://topcoder.atlassian.net/browse/TOP-1792 - Update uniNavi 'trigger' to support/use configurable object of button links
=> TOP-1792 add params to trigger

.circleci/config.yml, src/lib/components/user-area/UserArea.svelte
https://topcoder.atlassian.net/browse/TOP-2044 - always show the signin modal when triggered (no matter if user is logged in or not)
=> HOTFIX TOP-2044 - always show signin modal

.circleci/config.yml, src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/tool-selector-nav-items.ts
https://topcoder.atlassian.net/browse/TOP-1875
=> Remove SRM from navigation

src/lib/config/nav-menu/footer-nav-items.ts
https://topcoder.atlassian.net/browse/TOP-1875
=> PROD - Remove SRM from Tools menu

src/lib/components/user-area/SigninPopup.svelte, src/lib/components/user-area/UserMenu.svelte
https://topcoder.atlassian.net/browse/TOP-2004 - Add "login as customer" option in user menu.
=> TOP-2004 - add login as customer option in user menu

src/lib/components/user-area/UserMenu.svelte
Updates the url for the login as customer
=> TOP-2004 - update url for "login as customer option"

src/lib/components/LinksMenu.svelte, src/lib/components/SubMenu.module.scss, src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/main-navigation.config.ts, src/lib/marketing-navigation/MarketingNavigation.svelte
https://topcoder.atlassian.net/browse/LIT-2396 - Adds link to innovation challenges, under the "product" main nav link
Also makes sure the secondary navigation bar is removed and we're only showing the "dropdown" version.
=> LIT-2396 - add innovation challenge link

src/lib/components/LinksMenu.svelte, src/lib/components/SubMenu.module.scss, src/lib/marketing-navigation/components/NavigationBar.svelte
https://topcoder.atlassian.net/browse/LIT-2396 - make the sub-menu items bold when active
=> LIT-2396 - make sub-menu items bold when active

src/lib/components/LinksMenu.svelte, src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/main-navigation.config.ts
https://topcoder.atlassian.net/browse/LIT-2699 - remove the link to the pricing page
=> Release 09/24 - remove pricing page

.circleci/config.yml, src/lib/components/Maintenance.module.scss, src/lib/components/Maintenance.svelte, src/lib/components/user-area/UserArea.svelte, src/lib/marketing-navigation/MarketingNavigation.svelte, src/lib/tool-navigation/ToolNavigation.svelte
=> Maintenance banner

src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/footer-navigation/FooterNavigation.module.scss
=> QA feedback

src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/footer-nav-items.ts, src/lib/config/nav-menu/main-navigation.config.ts
https://topcoder.atlassian.net/browse/PM-347 - Remove/hide link for Customer Stories from Uninavi navigation
https://topcoder.atlassian.net/browse/PM-348 - Remove/hide link for Customer Stories and Blogs from Uninavi footer
=> PM-347 - hide customer stories & blog links

src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/footer-nav-items.ts, src/lib/config/nav-menu/main-navigation.config.ts
https://topcoder.atlassian.net/browse/PM-409 - adds back customer stories, different url
=> PM-409 - add customer stories urls

src/lib/config/nav-menu/all-nav-items.config.ts, src/lib/config/nav-menu/footer-nav-items.ts, src/lib/config/nav-menu/main-navigation.config.ts
As per https://topcoder.atlassian.net/browse/PM-406
=> Prod relese

src/lib/config/nav-menu/main-navigation.config.ts, src/lib/config/nav-menu/tool-selector-nav-items.ts
Temporarily remove the AI-Hub links
=> comment out ai-hub

src/lib/config/nav-menu/footer-nav-items.ts, src/lib/config/nav-menu/main-navigation.config.ts, src/lib/config/nav-menu/tool-selector-nav-items.ts
https://topcoder.atlassian.net/browse/PM-1000
=> PM1000 - add back ai minihub

src/lib/components/LinksMenu.module.scss
=> PM-924 - fix dropdown icon
