- package.json
- src/lib/app-context/auth-user.model.ts
- src/lib/components/UserAvatar.svelte
- types/lib/app-context/auth-user.model.d.ts
This PR updates the AuthUser `photoURL` property to be `photoUrl?`  It also adds the 3rd digit on the version so that yarn doesn't complain when trying to install the types.
> Types rollup config

- iac/uni-nav.deploy.yml
This PR adds the allowed origins to a custom response header policy that is assigned to the cloudfront distribution.
> PROD-3233 CORS -> master

- src/lib/config/index.ts
This PR uses `VITE_DEFAULT_HOST_URL` from the env to make the DEFAULT_HOST configurable by environment (eg. by setting VITE_DEFAULT_HOST_URL when building).
> Make default host configurable

- src/lib/components/LinksMenu.module.scss
- src/lib/components/LinksMenu.svelte
- src/lib/marketing-navigation/components/HoverMenu.module.scss
- src/lib/marketing-navigation/components/HoverMenu.svelte
- src/lib/marketing-navigation/components/NavigationBar.svelte
Improves the hover interaction for the marketing navigation. Moves the hover popup closer (in the DOM) to the navigation elements so I can do the whole interaction in css only.
Still relies on js for marking the hovered navigation item as active/in hover state.
> Improve interactions for the marketing navigation hover state

- .circleci/config.yml
This PR turns caching back on so that the CDN is automatically invalidated.
> PROD-3205 Turns caching back -> master

- public/assets/tools/sprite.svg
- src/lib/components/InlineSvg.svelte
- src/lib/components/LinksMenu.module.scss
- src/lib/components/ToolMenu.module.scss
- src/lib/utils/svg.ts
This pr fixes a few random issues found while testing the integrations:
- tool selector menu: svg sprite was not displaying icons because of the "hidden" class
- tool selector menu: needs to cache the sprite svg in memory, otherwise it is downloaded on each menu display
- tool selector menu: fix font issue for CTA buttons
- links menu: fix width constraint
> Integration fixes

- src/lib/components/tool-selector/ToolMenu.module.scss
- src/lib/components/tool-selector/ToolMenu.svelte
- src/lib/config/nav-menu/tool-selector-nav-items.ts
- src/lib/functions/nav-menu-item.model.ts
https://topcoder.atlassian.net/browse/PROD-3392
On mobile, adds a defined order (via flex order) for the grouped tools under talent.
> PROD-3392 - order tools groups on mobile

- src/lib/components/Accordion.svelte
- src/lib/functions/marketing-navigation.provider.ts
- src/lib/marketing-navigation/MarketingNavigation.svelte
- src/lib/marketing-navigation/components/NavigationBar.svelte
- src/lib/mobile-navigation/MobileNavigation.svelte
- src/lib/tool-navigation/ToolNavigation.svelte
- src/lib/utils/routes.ts
https://topcoder.atlassian.net/browse/PROD-3391
Update mobile navigation to receive the menu items from the main navigation component (either tool or marketing).
Hides the sub nav marketing items on mobile for the tool navigation.
> PROD-3391 - mobile nav - remove sub menus for tool navs

- src/lib/components/LinksMenu.module.scss
- src/lib/components/tool-selector/ToolMenu.module.scss
- src/lib/components/tool-selector/ToolMenu.svelte
Fixes some issues mentioned on the standup call.
- hover color for all navigation items should be white
- 2nd and 3rd navigations should show the items as title case instead of uppercase
- fix the line height for the items in the tool menu
> Ux fixes -> dev

- src/lib/config/nav-menu/marketing-nav-items.ts
Switches the nav type to marketing when accessing articles from the marketing>talent>learn>Articles.
> Switch nav type to marketing for articles -> dev

- src/lib/components/tool-selector/ToolMenu.svelte
Fixes extra space in cta buttons
Before:
After:
> Fix cta button -> dev

- src/lib/utils/routes.ts
Fixes the method that matches current url to nav items. It now ignores the current page url's query params &  hash strings. 
The issue:
- go to https://qa-community-app.topcoder-dev.com/thrive?navTool=marketing
- talent/learn/articles navigation item should be highlighted, but it is not
> Fix routeMatch method - ignore search query/hash strings -> dev

- src/lib/marketing-navigation/components/HoverMenu.module.scss
- src/lib/styles/_colors.scss
- src/lib/styles/_palette.scss
https://topcoder.atlassian.net/browse/PROD-3910
Updates the color palette for the hover menu.
Also adds the TC color palette to be used later on to refactor color uses in all the codebase.
> PROD-3910 - update color palette for hover menu -> dev

- .circleci/config.yml
An update was made to the production S3 env file to correct the community URL. In order to deploy this change we need to comment-out the type update during the build/deploy.
> Comments out types update for hotfix deploy > master

- src/lib/tool-navigation/ToolNavigation.module.scss
- src/lib/tool-navigation/ToolNavigation.svelte
- src/lib/tool-navigation/tool-nav-separator/ToolNavSeparator.module.scss
- src/lib/tool-navigation/tool-nav-separator/ToolNavSeparator.svelte
https://topcoder.atlassian.net/browse/PROD-4020
Updates the behavior of the main menu reveal slider that's under the tool navigation:
- slider defaults to collapsed position (so on initialization we don't see the slider animation anymore)
- when slider is collapsed, the clicks for main menu are ignored (pointer-events: none)
> PROD-4020 - update tool's menu review slider behavior -> dev

- src/lib/utils/fonts.ts
https://topcoder.atlassian.net/browse/UN-682
This PR deals with the fact that `document.fonts.check` has a different behavior in chromium vs non-chromium browsers. In non-chromium browsers this method is always returning true to preserve user's privacy. And this basically makes the method useless.
In this PR I created a custom method to check if a font is loaded or not. It's based on a simple reasoning that different fonts will render a text in different sizes. This is especially true in our use case (serif vs Barllow & Roboto are totally different). So it is accurate enough for our use case.
> UN-682 - improve the font loaded check function -> dev

- iac/deploy-stack.sh
- iac/uni-nav.deploy.yml
Adds `learn.topcoder.com` to CORS policy.
NOTE: needs to be deployed using [iac/deploy-stack.sh](/topcoder-platform/universal-navigation/tree/dev/iac/README.md)
> Add CORS for learn.topcoder subdomain

- src/lib/components/user-area/ProgressCicle.svelte
- src/lib/components/user-area/UserAvatar.module.scss
https://topcoder.atlassian.net/browse/MP-78
Fixes the user profile progress bar on safari: safari doesn't support negative values for svg `stroke-dashoffset` so had to come with a workaround that seems to work well.
> MP-78 - fix progress bar for safari

- src/lib/components/user-area/UserArea.svelte
- src/lib/config/hosts.ts
- src/lib/config/profile-toasts.config.ts
- src/lib/functions/profile-nudges.ts
- src/lib/nudge-app/toast-manager.ts
- types/src/lib/config/hosts.d.ts
- types/src/lib/config/profile-toasts.config.d.ts
- types/src/lib/functions/profile-nudges.d.ts
https://topcoder.atlassian.net/browse/MP-188
Dismisses the profile nudges on certain domains by matching the configured dismissed hosts to the current URL:
- Onboarding (onboarding.topcoder-dev.com)
- Profiles (profiles.topcoder-dev.com)
- Work Manager (challenges.topcoder-dev.com)
- Talent search (talent-search.topcoder-dev.com)
- Connect (connect.topcoder-dev.com)
> MP-188 - dismiss profile nudges on certain domains -> dev

- src/lib/components/user-area/UserMenu.svelte
Small update: hide the profile nudge in the user dropdown menu when user is on a dismissed domain
> MP-188 - in the user dropdown menu do not show the nudge -> dev

- src/lib/components/user-area/UserArea.svelte
- src/lib/components/user-area/UserMenu.svelte
- src/lib/config/profile-toasts.config.ts
- src/lib/functions/profile-nudges.ts
- types/src/lib/config/profile-toasts.config.d.ts
Related JIRA tickets:
https://topcoder.atlassian.net/browse/MP-323 - Show progress ring around the avatar across all applications
https://topcoder.atlassian.net/browse/MP-328 - Red dot near the Profiles is displayed for Customer account
This PR  fetches the user profile completeness on all domains, but dismisses it for customer users. The toast nudges are now hidden based on app hostname.
> Fetch user completeness data on all domains, but not for customer users

- index.html
- src/lib/app-context/app-context.functions.ts
- src/lib/app-context/tool-config.model.ts
- src/lib/components/LinksMenu.module.scss
- src/lib/components/LinksMenu.svelte
- src/lib/components/VerticalSeparator.module.scss
- src/lib/config/nav-menu/tool-nav-items.ts
- src/lib/functions/tool-navigation.provider.ts
- src/lib/tool-navigation/SalesCtaButtons.svelte
- src/lib/tool-navigation/ToolNavigation.svelte
- src/main.ts
- types/src/lib/app-context/app-context.functions.d.ts
- types/src/lib/app-context/tool-config.model.d.ts
- types/src/lib/config/nav-menu/tool-nav-items.d.ts
- types/src/lib/functions/tool-navigation.provider.d.ts
- types/src/main.d.ts
https://topcoder.atlassian.net/browse/TAL-69 - Add sales CTAs to the header in Talent Search app
Adds a config to enable displaying of sales CTA buttons inside the Tools navbar.
A few conditions that have to be met for  this to be displayed:
- configuration flag `showSalesCta` needs to be set to `true`
- user must either be a customer or not logged in at all
- on mobile devices the CTAs are hidden (according to discussions & figma - there's not enough room)
> TAL-69 - Add sales cta buttons for ToolsNavbar

- src/lib/config/hosts.ts
- src/lib/config/nav-menu/all-nav-items.config.ts
- types/src/lib/config/hosts.d.ts
We need to do a uninav release before the wallet app is ready, so this PR is undoing the linking to the WalletApp. It will be easily restored once we have the wallet ready.
> Restore payment app as "PACTS" instead of wallet

- src/lib/config/hosts.ts
- src/lib/config/nav-menu/all-nav-items.config.ts
- types/src/lib/config/hosts.d.ts
This reverts commit [cfab3a59fdce8e7cf0f264022d4c3b789cfef9af](https://github.com/topcoder-platform/universal-navigation/commit/cfab3a59fdce8e7cf0f264022d4c3b789cfef9af).
This is in order to release the uninav with the WalletApp enabled.
> Revert "Restore payment app as "PACTS" instead of wallet"

- src/lib/config/nav-menu/footer-nav-items.ts
https://topcoder.atlassian.net/browse/TOP-1476 - Clean up topcoder.com footer
This pr removes the "talent spotlight" link in footer
> Remove talent spotlight in footer

- src/lib/components/user-area/UserArea.svelte
- src/lib/utils/pubsub.ts
- src/main.ts
- types/src/lib/utils/pubsub.d.ts
- types/src/main.d.ts
This PR adds a method on uninav that allows anyone to trigger the "signin" modal within uninav.
The call will look like:
- signup: `tcUniNav('trigger', 'signup')`
- login: `tcUniNav('trigger', 'login')`
> Adds a way to trigger the uninav's signin modal from outside -> dev

- src/lib/config/hosts.ts
- src/lib/config/nav-menu/all-nav-items.config.ts
- src/lib/config/nav-menu/footer-nav-items.ts
- src/lib/config/nav-menu/main-navigation.config.ts
- types/src/lib/config/hosts.d.ts
- https://topcoder.atlassian.net/browse/TOP-1650 - Add Talent to top level UniNav
Adds new section to top UniNav called “Talent” next to Demo. It will link to www.topcoder.about-talent.com
- https://topcoder.atlassian.net/browse/TOP-1651 - Add Talent to the footer after Expertise
- https://topcoder.atlassian.net/browse/TOP-1654 - Remove "About Topcoder" in Footer
- https://topcoder.atlassian.net/browse/TOP-1652 - Updates Expertise link in footer to topcoder.com/ai
> TOP-1650 - update talent links
